In [0]:
%tensorflow_version 2.x
import tensorflow as tf

###Matrix Multiplication in TensorFlow 

In [9]:
print(tf.__version__)

2.0.0


mat_A : random normal distribution 

mat_B : truncated normal distribution



In [0]:
mat_A= tf.random.normal(shape=(2,3), mean=10,stddev=2)
mat_B = tf.random.truncated_normal(shape=(3,5), mean=12, stddev=3)

In [11]:
print(mat_A)
print(mat_B)

tf.Tensor(
[[10.993943  8.320559 12.068962]
 [ 9.505297 11.37554  10.118107]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[13.155802 14.156095 14.867334 10.181187 14.815641]
 [ 6.932066 11.482668  9.380983 11.0412    7.519198]
 [13.485396 12.294671 15.77387   9.886871 15.023266]], shape=(3, 5), dtype=float32)


In [0]:
mat_C=tf.matmul(mat_A,mat_B)

In [13]:
print("Result is :",mat_C)

Result is : tf.Tensor(
[[365.06754 399.55743 431.87988 323.1246  406.76147]
 [340.35248 389.57822 407.63388 322.41122 378.36902]], shape=(2, 5), dtype=float32)
